baseURL = 'https://blog.kelvin.ma/'
languageCode = 'en-us'
title = "Kelvin's Blog"
theme = 'hugo-coder'

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"


# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 1
url = "https://x.com/KelvinHMa"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/kelvin-ma-6512bb12/"

[[params.social]]
name = "GitHub"
icon = "fa-brands fa-github fa-2x"
weight = 3
url = "https://github.com/PureSin/"

[[params.social]]
name = "Bluesky"
icon = "fa-solid fa-cloud fa-2x"
weight = 4
url = "https://bsky.app/profile/puresin14.bsky.social"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"